MIN_DIST_MOV = 50
BUFFER_LINE = 10
LENGTH_AVG_DIR = 10
DEGREE_RANGE_CANDIDATE = 45
PERCENTAGE_RANGE_VALID = 0.4
MAX_FRAMES_REMOVED = 100
MAX_DIST_FALSE_PLACE = 5
MIN_TRACK_EXIT = 10
ASPECT_RATIO = 0 #not used
THRESH_VALID_PREDICT_POINT = 100 #calculated automatically
LINES_RANGE = 85
MIN_DIRECTION_DIST = 10
MAX_BUFFER_MOVS = 10
MIN_DIST_CANDIDATE = 5
MIN_DIST_ENTRY_EXIT = 20
THRESH_VALID_PREDICT_BOX = 10 #calculated automatically


